### PR TITLE
Add runtime options interface

### PR DESCRIPTION
**Pull request by TinoDidriksen**
This PR adds code to fascilitate HFST using Foma directly ( https://github.com/hfst/hfst/issues/485#issuecomment-713512736 & https://github.com/hfst/hfst/tree/foma ).

<s>`sigmasizes+3` to `sigmasizes+30` is trivial - HFST just needs more memory sometimes, and this must be relevant for other users.</s>

But the bigger change is adding API `fsm_set_option()` and `fsm_get_option()` because HFST needs to disable a piece of Foma's code. And I figured if I'm adding a way to set one option, I might as well make it extensible for potential future options.

<s>The option should maybe be renamed - I don't know what the code semantically does, so I named it dot-hash-dot because that's what it mechanically does.</s>

If you can see a better way to accomplish this then by all means do, but this works.

### CODE REVIEW

**Comment by AmbientLighter** [comment]
@TinoDidriksen  dot-hash-dot stands for word boundary symbol https://github.com/mhulden/foma/blob/master/foma/docs/simpleintro.md#word-boundaries-in-rewrite-rules
IIUC This code adds word boundary symbol to sigma if it doesn't contain it yet. Therefore I'd suggest to rename it to `skip_merge_dothashdot` to `skip_word_boundary_symbol`

**Comment by TinoDidriksen** [comment]
Renamed.

**Comment by AmbientLighter** [comment]
As about segfault related to sigmasize overflow, it looks like both 3 and 30 magic numbers are arbitrary. It may work for large enough sigmas until we hit even bigger sigma. Looking [at its usage](https://github.com/hfst/hfst/blob/a40be44f9205df89b2f7b9cc0051466413933690/back-ends/foma/constructions.c#L988-L989), 
it looks like there's `sigma->number` which exceeds 3 and may exceed 30. Therefore we may find maximum value of `sigma->number` of both `net1` and `net2` and use that number instead of 3 or 30.
If it is possible, it would be best to verify solution on some real world dataset which is known to fail with current Foma.

**Comment by AmbientLighter** [comment]
FYI I've created related pull request in HFST repo which attempts to try this bug:
https://github.com/hfst/hfst/pull/530/files

**Comment by AmbientLighter** [comment]
@TinoDidriksen Could you please fix merge conflicts?

**Comment by TinoDidriksen** [comment]
Done.

**Comment by AmbientLighter** [comment]
@mhulden This pull request looks good to me. What do you think?

**Comment by mhulden** [comment]
Not currently passing build checks. Fixable?

**Comment by TinoDidriksen** [comment]
It had come out of sync with the HFST changes - try now.

**Pull request merged**
