### PR TITLE
Add CMakeLists.txt

### PR DESCRIPTION
**Pull request by ttti07**
[CMake](https://cmake.org/) is a cross-platform family of tools designed to build, test and package software.
It is one of the de facto standard tools in C/C++ projects today.

### Typical Usage
```sh
cd foma
mkdir build
cd build
cmake ..
make -j install
```

### Link to foma library
in my_project/CMakeLists.txt
```cmake
find_package(foma)

add_library(my_app blarblar.c)
target_link_libraries(my_app foma)

add_library(my_app2 foobar.c  $<TARGET_OBJECTS:foma>)
```

```sh
cd my_project
mkdir build
cd build
cmake ..
# If you did not install foma in the system path, you should provide some hint to cmake command, like below.
# cmake .. -Dfoma_DIR=/your/path/to/apps/lib/cmake/foma
make -j
```

### Otherwise, just embed foma source codes on your project
```
cd my_project
git submodule add https://github.com/mhulden/foma.git third_party/foma
git submodule init
git submodule update
```

in my_project/CMakeLists.txt
```cmake
add_subdirectory(third_party/foma EXCLUDE_FROM_ALL)

add_library(my_app blarblar.c)
target_link_libraries(my_app foma)

add_library(my_app2 foobar.c  $<TARGET_OBJECTS:foma>)
```

Then run cmake and make, the same as above.

### CODE REVIEW

**Comment by AmbientLighter** [comment]
@ttti07 Would be nice to check if it is working for different OS by calling CMake from CI workflow.

**Comment by ttti07** [comment]
@AmbientLighter I added some commands to build.yml. Thanks for your guide.

**Comment by wincentbalin** [comment]
Isn't this pull request superceded by pull request #141?

**Comment by AmbientLighter** [comment]
Yes, it makes sense to close this pull request.

**Pull request closed without merging**
